name: workers-ne
on: [push, pull_request]
# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      # действие проверяет содержимое хранилища, в котором
      # размещен вызывающий рабочий процесс, а не вызываемый рабочий процесс.
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ matrix.node-version }}

      # - name: Install dependencies
      #   run: cd src/app/frontend && yarn run build:dev
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build:dev

      - name: Setup Pages
        uses: actions/configure-pages@v3.0.6

      - name: Upload artifact

        uses: actions/upload-artifact@v3.1.3

        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: dist
